name: CI
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          ruff check .
          ruff format --check .
      - name: Type check
        run: mypy --strict src tests scripts
      - name: Tests
        run: pytest -q
      - name: Build package
        run: python -m build
      - name: ADR lint
        run: python scripts/lint_adrs.py
